/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ehu.isad;

import ehu.isad.controller.ui.*;
import ehu.isad.model.Herrialdea;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

import java.io.IOException;

public class Main extends Application {

    private Parent EurobisioaUI;
    private Parent HerrialdeaHautatuUI;
    private Parent ErroreaUI;
    private Parent BozkaketaUI;

    private Stage stage;

    private Scene sceneHasiera;
    private Scene sceneHerrialdeHautatu;
    private Scene sceneErrorea;


    private HasieraKud hasieraKud;
    private HerrialdeaHautatuKud herrialdeaHautatuKud;
    private ErroreaKud erroreaKud;


    @Override
    public void start(Stage primaryStage) throws Exception {
        stage = primaryStage;
        pantailakKargatu();
        stage.setTitle("Eurobisioa");
        stage.setScene(sceneHasiera);
        stage.show();
    }

    private void pantailakKargatu() throws IOException {
        FXMLLoader loaderEurobisioa = new FXMLLoader(getClass().getResource("/LehenengoPantaila.fxml"));
        EurobisioaUI = (Parent) loaderEurobisioa.load();
        hasieraKud = loaderEurobisioa.getController();
        hasieraKud.setMainApp(this);
        sceneHasiera = new Scene(EurobisioaUI);

        FXMLLoader loaderHerrialdeaHautatu = new FXMLLoader(getClass().getResource("/HerrialdeaHautatu.fxml"));
        HerrialdeaHautatuUI = (Parent) loaderHerrialdeaHautatu.load();
        herrialdeaHautatuKud = loaderHerrialdeaHautatu.getController();
        herrialdeaHautatuKud.setMainApp(this);
        sceneHerrialdeHautatu = new Scene(HerrialdeaHautatuUI);

        FXMLLoader loaderErrorea = new FXMLLoader(getClass().getResource("/ErroreaBozkaketa.fxml"));
        ErroreaUI = (Parent) loaderErrorea.load();
        erroreaKud = loaderErrorea.getController();
        erroreaKud.setMainApp(this);
        sceneErrorea = new Scene(ErroreaUI);
    }


    public void herrialdeaHautatuErakutsi(){
        stage.setTitle("Herrialdeak");
        stage.setScene(sceneHerrialdeHautatu);
        stage.show();
    }

    public void erroreaBozkaketaErakutsi(Herrialdea herrialdea){
        stage.setTitle("Errorea bozkaketan");
        erroreaKud.datuakJarri(herrialdea);
        stage.setScene(sceneErrorea);
        stage.show();
    }
}
