/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ehu.isad;

import ehu.isad.controller.ui.*;
import ehu.isad.model.Herrialdea;
import ehu.isad.utils.Utils;
import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.stage.Stage;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;

public class Main extends Application {

    private Parent EurobisioaUI;
    private Parent HerrialdeaHautatuUI;
    private Parent ErroreaUI;
    private Parent BozkaketaUI;
    private Parent Top3UI;

    private Stage stage;

    private Scene sceneHasiera;
    private Scene sceneHerrialdeHautatu;
    private Scene sceneErrorea;
    private Scene sceneBozkatu;
    private Scene sceneTop3;


    private HasieraKud hasieraKud;
    private HerrialdeaHautatuKud herrialdeaHautatuKud;
    private ErroreaKud erroreaKud;
    private BozkaketaKud bozkaketaKud;
    private Top3Kud top3Kud;

    @Override
    public void start(Stage primaryStage) throws Exception {
        stage = primaryStage;
        pantailakKargatu();
        stage.setTitle("Eurobisioa");
        stage.setScene(sceneHasiera);
        stage.show();
    }

    private void pantailakKargatu() throws IOException {
        FXMLLoader loaderEurobisioa = new FXMLLoader(getClass().getResource("/LehenengoPantaila.fxml"));
        EurobisioaUI = (Parent) loaderEurobisioa.load();
        hasieraKud = loaderEurobisioa.getController();
        hasieraKud.setMainApp(this);
        sceneHasiera = new Scene(EurobisioaUI);

        FXMLLoader loaderHerrialdeaHautatu = new FXMLLoader(getClass().getResource("/HerrialdeaHautatu.fxml"));
        HerrialdeaHautatuUI = (Parent) loaderHerrialdeaHautatu.load();
        herrialdeaHautatuKud = loaderHerrialdeaHautatu.getController();
        herrialdeaHautatuKud.setMainApp(this);
        sceneHerrialdeHautatu = new Scene(HerrialdeaHautatuUI);

        FXMLLoader loaderErrorea = new FXMLLoader(getClass().getResource("/ErroreaBozkaketa.fxml"));
        ErroreaUI = (Parent) loaderErrorea.load();
        erroreaKud = loaderErrorea.getController();
        erroreaKud.setMainApp(this);
        sceneErrorea = new Scene(ErroreaUI);

        FXMLLoader loaderBozkatu = new FXMLLoader(getClass().getResource("/Bozkatu.fxml"));
        BozkaketaUI = (Parent) loaderBozkatu.load();
        bozkaketaKud = loaderBozkatu.getController();
        bozkaketaKud.setMainApp(this);
        sceneBozkatu = new Scene(BozkaketaUI);

        FXMLLoader loaderTop3 = new FXMLLoader(getClass().getResource("/Top3.fxml"));
        Top3UI = (Parent) loaderTop3.load();
        top3Kud = loaderTop3.getController();
        top3Kud.setMainApp(this);
        sceneTop3 = new Scene(Top3UI);
    }


    public void herrialdeaHautatuErakutsi(){
        stage.setTitle("Herrialdeak");
        stage.setScene(sceneHerrialdeHautatu);
        stage.show();
    }

    public void erroreaBozkaketaErakutsi(Herrialdea herrialdea){
        stage.setTitle("Errorea bozkaketan");
        erroreaKud.erroreaErakutsi(herrialdea);
        stage.setScene(sceneErrorea);
        stage.show();
    }

    public void bozkatuErakutsi(Herrialdea herrialdea){
        stage.setTitle("Puntuak banatu");
        bozkaketaKud.herrialdeBozkatzailea(herrialdea.getIzena());
        bozkaketaKud.norkBozkatu(herrialdea);
        stage.setScene(sceneBozkatu);
        stage.show();
    }

    public void top3Erakutsi(){
        stage.setTitle("TOP 3");
        stage.setScene(sceneTop3);
        stage.show();
    }

    /*public void aplikazioaItxi(){
        System.exit(0);
    }*/
}
